Anti-Malware / Antivirus Module
-------------------------------

✅ Automatically scan every newly added document

✅ Automatically tag document with scan status and timestamp 

[discrete]
Overview
~~~~~~~~

image::antivirus-architecture.svg[Antivirus Architecture,700,700]

Antivirus is a FormKiQ Module that provides document security by detecting trojans, viruses, malware & other malicious threats for every newly created document, using the http://www.clamav.net[ClamAV] antivirus engine.

Using FormKiQ's Document Events, each newly-created document is automatically added to a ClamAV Scanning SQS queue. An AWS Lambda function for ClamAV virus scanning pulls each document from the SQS queue and scans it for trojans, viruses, malware, and other malicious threats. The results from the scan are added as S3 Tags to the document, and are also attached to the document in DynamoDB. In addition, a message is posted to an ClamAV Scan Events SNS topic which allows other systems to be notified of the document's scan status.

====
_**Use Cases:**_
[loweralpha] 
. _If you have received certain compliance goals that require antivirus scanning of all documents used by the organization, this module can meet those goals without any additional effort_
. _If you receive documents from external sources, whether through the FormKiQ API's public endpoints or optional Enterprise Add-On Modules such as Document Email Processing, antivirus scanning will help to safeguard both your documents within FormKiQ and any documents you export from FormKiQ_
====

[discrete]
API
~~~

**You can view the Antivirus Module endpoint in the link:../api/README.html#antivirus[API Reference].**