site:
  title: FormKiQ Documentation
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://docs.formkiq.com
  start_page: docs::index.adoc
content:
  edit_url: false
  sources:
  - url: .
    start_path: docs
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: ./build/ui-bundle.zip
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    #url: https://github.com/evidentsystems/docs-ui/releases/download/v0.1.6/ui-bundle.zip
    #snapshot: true
