= FormKiQ HowTo
:navtitle: HowTo
:title: FormKiQ HowTo
:docinfo: shared
:data-uri:
:toc: left
:toclevels: 2
:sectanchors:
:sectlinks:
:sectnums:
:favicon: favicon.ico

These HowTo Guides provide use cases and how do perform specific tasks using the FormKiQ API.

== xref:howto:jwt-authentication-token.adoc[Getting an JWT Authentication Token]

This xref:howto:jwt-authentication-token.adoc[How-To] will take you through getting an authentication token (JWT) that can be used to access the FormKiQ API.

Time: 5 minutes

== xref:howto:api-add-documents.adoc[Adding Document using FormKiQ API]

This xref:howto:api-add-documents.adoc[How-To] will take you through different way to add documents using the the FormKiQ API.

Time: 15 minutes

== xref:howto:api-add-document-tags.adoc[Adding Document Tags using FormKiQ API]

This xref:howto:api-add-document-tags.adoc[How-To] will take you through different way to add tags to documents using the the FormKiQ API.

Time: 15 minutes

== xref:howto:api-document-search.adoc[Searching for Documents using FormKiQ API]

This xref:howto:api-document-search.adoc[How-To] will take you through different way to search for documents using the the FormKiQ API.

Time: 15 minutes

== xref:howto:api-document-actions.adoc[How to use Document Actions]

This xref:howto:api-document-actions.adoc[How-To] shows you how you can use FormKiQ's Document Actions to automate your document process.

Time: 15 minutes
