==== Data Storage

The data storage component divides into two parts, the document storage and the document metadata storage.

===== Document Storage

Document storage is done using Amazon's S3 service. S3 provides industry-leading https://docs.aws.amazon.com/AmazonS3/latest/userguide/DataDurability.html[data durability and data protection] for all of your documents. 

Description of S3 Buckets:

|=======================================================================
| Bucket | Description                
| `Staging` | A temporary holding place for documents waiting for processing 
| `Documents` | The permanent post-processing document storage
|=======================================================================

===== Metadata Storage

Each document's metadata is stored in Amazon's NoSQL database https://aws.amazon.com/dynamodb/[DynamoDB]. DynamoDB is a fast, flexible NoSQL database service for single-digit millisecond performance at any scale. It is also fully-managed by AWS, so there are no database servers to manage.

Description of DynamoDB Tables:

|=======================================================================
| Bucket | Description                
| `Documents` | Stores a record of all documents along with all metadata and tenant information
| `Caching` | A storage for temporary data
|=======================================================================

