
==== Document Events

Document events are a powerful feature of FormKiQ Core. These events allow operations to be triggered on documents automatically, whenever a change occurs. For example, when a document is created, a document event can be triggered to perform one or many actions, such as:

- sending an email notification
- scanning for viruses
- inserting data into a database
- etc. 

Document event are created and sent through https://aws.amazon.com/sns[Amazon Simple Notification Service (SNS)]. Amazon SNS is a messaging service that can be used for application-to-application communication. FormKiQ Core uses it as a publish/subscribe service, where applications can listen to the SNS service and be notified about different document events.

FormKiQ Core creates a single `SnsDocumentEvent` topic where all document events are sent. You can then use https://docs.aws.amazon.com/sns/latest/dg/sns-subscription-filter-policies.html[Amazon SNS subscription filter policies] to set up actions for a specific type of event.

FormKiQ Core provides the following message attributes that you can filter on:

|=======================================================================
| Message Attribute | Possible Value(s) | Description                
| `type` | create, delete, update | Document Event(s) for create, update, or delete document
| `siteId` | default, (custom siteId) | Site Tenant Document Event was created in
|=======================================================================

See https://docs.aws.amazon.com/sns/latest/dg/sns-subscription-filter-policies.html
