==== Authentication

Security is of the utmost importance for any system. However, flexibility is required to be able to integrate securely with other systems. This is why both JSON Web Tokens (JWTs) and AWS Identity and Access Management (IAM) are supported methods for authentication.

===== JSON Web Tokens (JWTs)

JSON Web Tokens (JWTs) as a part of https://openid.net/specs/openid-connect-core-1_0.html[OpenID Connect (OIDC)] and https://oauth.net/2/[OAuth 2.0] frameworks to restrict client access to the APIs.

https://aws.amazon.com/cognito[Amazon Cognito] is used as the default JWT authorizer to ensure the JWT tokens are authentic and valid. However, any other JWT authorizer can be used.

===== AWS Identity and Access Management (IAM)

AWS Identity and Access Management (IAM) is the access control used across all of AWS services. Using IAM policies, one could https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-iam-policy-examples-for-api-execution.html[provide a service the ability to call any API]. This allows for an automated method for backend services to integrate with the FormKiQ API, with no need to retrieve a JWT token first.
