==== Data Storage

The data storage component is divides into two parts, the document storage and the document's meta data storage.

===== Document Storage

Document storage is done using Amazon's S3 service. S3 provides industry leading data  https://docs.aws.amazon.com/AmazonS3/latest/userguide/DataDurability.html[durability and data protection] for all your documents. 

Description of S3 Buckets:

|=======================================================================
| Bucket | Description                
| `Staging` | A temporary holding place for documents waiting for processing 
| `Documents` | The permanent post-processing document storage
|=======================================================================

===== Meta Data Storage

Document's meta data is stores in Amazon's NoSQL database https://aws.amazon.com/dynamodb/[DynamoDB]. DynamoDB is a fast, flexible NoSQL database service for single-digit millisecond performance at any scale. It is also a fully managed database by AWS so there's no servers to manage.

Description of DynamoDB Tables:

|=======================================================================
| Bucket | Description                
| `Documents` | Stores a record of all documents along with all meta data and tenant information
| `Caching` | A storage for temporary data
|=======================================================================

