
==== Document Events

Document events are a powerful feature of FormKiQ Core. This feature allows operations to be triggered on documents automatically on a change event. For example, when a document is created, a document event could trigger it to:

- send an email notification
- scan for viruses
- insert data into a database
- etc. 

Document event are created and sent through https://aws.amazon.com/sns[Amazon Simple Notification Service (SNS)]. Amazon SNS is a messaging service that can be used for application to application communication. FormKiQ Core uses it as a publish/subscribe service, where applications can listen to the SNS service and be notified about different document events.

FormKiQ Core creates a single `SnsDocumentEvent` topic where all documents events are sent. You can use https://docs.aws.amazon.com/sns/latest/dg/sns-subscription-filter-policies.html[Amazon SNS subscription filter policies].

FormKiQ Core provides the following message attributes you can filter on.

|=======================================================================
| Message Attribute | Possible Value(s) | Description                
| `type` | create, delete, update | Document Event(s) for create, update, or delete document
| `siteId` | default, (custom siteId) | Site Tenant Document Event was created in
|=======================================================================

See https://docs.aws.amazon.com/sns/latest/dg/sns-subscription-filter-policies.html
