import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api-reference/formkiq-api-jwt",
    },
    {
      type: "category",
      label: "System Management",
      items: [
        {
          type: "doc",
          id: "api-reference/get-version",
          label: "Get FormKiQ version",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-sites",
          label: "Get site(s) access",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-site",
          label: "Add Site",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/update-site",
          label: "Update Site",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/get-site-groups",
          label: "Get group(s) and permissions belonging to site",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-site-group",
          label: "Get group and permissions belonging to site",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/delete-site-group",
          label: "Deletes Site Group and permissions",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/set-site-group-permissions",
          label: "Set Site's Group Permissions",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/get-opensearch-index",
          label: "Get site(s) OpenSearch index settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/set-opensearch-index",
          label: "Set site(s) OpenSearch index settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/delete-opensearch-index",
          label: "Deletes site(s) OpenSearch index",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-configuration",
          label: "Get site configuration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/update-configuration",
          label: "Update site configuration",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/get-api-keys",
          label: "Get API Keys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-api-key",
          label: "Add API Key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/delete-api-key",
          label: "Delete API Key",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-locales",
          label: "Get Locales",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-locale",
          label: "Add Locale",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/delete-locale",
          label: "Delete Locale",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-locale-resource-items",
          label: "Get Resource Items by Locale",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-locale-resource-item",
          label: "Add Locale Resource Item",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-locale-resource-item",
          label: "Get Resource Item by Locale",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/set-locale-resource-item",
          label: "Set Locale Resource Item",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/delete-locale-resource-item",
          label: "Delete Local Resource Item",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api-reference/get-sites-schema",
          label: "Get Sites Schema",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/set-sites-schema",
          label: "Set Sites Schema",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/get-sites-schema-attribute-allowed-values",
          label: "Get Attribute Allowed Values",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-sites-classifications",
          label: "Get Sites Classifications",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-classification",
          label: "Add Classification",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-classification",
          label: "Get Classification",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/delete-classification",
          label: "Delete Classification",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/set-classification",
          label: "Set Classification",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/get-classification-attribute-allowed-values",
          label: "Get Classification's Attribute Allowed Values",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Access Control",
      items: [
        {
          type: "doc",
          id: "api-reference/get-opa-access-policies",
          label: "Get OPAs Access Policies",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-opa-access-policy",
          label: "Get OPA Access Policy",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-opa-access-policy-items",
          label: "Get OPA Access Policy Items",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/set-opa-access-policy-items",
          label: "Set opa access policy items, can only be requested with ADMIN privileges",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/delete-opa-access-policy-items",
          label: "Delete OPA Access Policy Items",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Documents",
      items: [
        {
          type: "doc",
          id: "api-reference/get-documents",
          label: "Get Documents listing",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-document",
          label: "Add new document",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-document",
          label: "Get document",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/update-document",
          label: "Update document",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/delete-document",
          label: "Delete document",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/purge-document",
          label: "Purge document",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-document-content",
          label: "Get document's contents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-document-url",
          label: "Get document content url",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-document-upload",
          label: "Get url to add large document",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-document-upload",
          label: "Add large document",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-document-id-upload",
          label: "Get url to update large document",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/set-document-restore",
          label: "Restore soft deleted document",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/compress-documents",
          label: "Compress multiple documents into a .zip file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-document-syncs",
          label: "Get document syncs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-published-document-content",
          label: "Get published document's contents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/delete-published-document-content",
          label: "Delete published document's contents",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Document Attributes",
      items: [
        {
          type: "doc",
          id: "api-reference/get-document-attributes",
          label: "Get document's attributes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-document-attributes",
          label: "Add attribute to document",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/set-document-attributes",
          label: "Set document's attributes",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/get-document-attribute",
          label: "Get document attribute by key",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/set-document-attribute-value",
          label: "Set document's attributes value",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/delete-document-attribute",
          label: "Delete document attribute",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/delete-document-attribute-and-value",
          label: "Delete document's attribute value",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-document-attribute-versions",
          label: "Get document attribute's versions",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Document Tags",
      items: [
        {
          type: "doc",
          id: "api-reference/get-document-tags",
          label: "Get document's tags",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-document-tags",
          label: "Add tag to document",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/update-document-tags",
          label: "Update document tags",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/set-document-tags",
          label: "Set document's tags",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/get-document-tag",
          label: "Get document tag by key",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/set-document-tag",
          label: "Update document tag value(s)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/delete-document-tag",
          label: "Delete document tag",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/delete-document-tag-and-value",
          label: "Delete document's tag value",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/update-matching-document-tags",
          label: "Mass Update document tag(s)",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Attributes",
      items: [
        {
          type: "doc",
          id: "api-reference/get-attributes",
          label: "Get Attributes listing",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-attribute",
          label: "Add new attribute",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-attribute",
          label: "Get Attribute",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/delete-attribute",
          label: "Delete attribute",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-attribute-allowed-values",
          label: "Get Attribute Allowed Values",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Document Search",
      items: [
        {
          type: "doc",
          id: "api-reference/document-search",
          label: "Document search",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Advanced Document Search",
      items: [
        {
          type: "doc",
          id: "api-reference/search-fulltext",
          label: "Document full-text search",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/query-fulltext",
          label: "Direct opensearch search API",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-document-fulltext",
          label: "Get document's full-text",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/delete-document-fulltext",
          label: "Delete document full-text",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/set-document-fulltext",
          label: "Set document's full-text",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/add-document-fulltext",
          label: "Add document's full-text",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/update-document-fulltext",
          label: "Update document's full-text",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/delete-document-fulltext-tag",
          label: "Delete document full-text tag",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/delete-document-fulltext-tag-and-value",
          label: "Delete document full-text tag/value",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Document Actions",
      items: [
        {
          type: "doc",
          id: "api-reference/get-document-actions",
          label: "Get document actions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-document-actions",
          label: "Add document action",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/add-document-retry-action",
          label: "Retries failed document action(s)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Document OCR",
      items: [
        {
          type: "doc",
          id: "api-reference/get-document-ocr",
          label: "Get document ocr content",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-document-ocr",
          label: "Perform document ocr",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/set-document-ocr",
          label: "Set document ocr result",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/delete-document-ocr",
          label: "Delete document ocr",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Document Versions",
      items: [
        {
          type: "doc",
          id: "api-reference/get-document-versions",
          label: "Get document's versions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/set-document-version",
          label: "Set version of document",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/delete-document-version",
          label: "Delete document version",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Document Folders",
      items: [
        {
          type: "doc",
          id: "api-reference/get-folder-documents",
          label: "Get document folders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-folder",
          label: "Add document folder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/delete-folder",
          label: "Delete document folder",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Document Shares",
      items: [
        {
          type: "doc",
          id: "api-reference/get-user-shares",
          label: "Get user shared folders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-folder-share",
          label: "Add folder share",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/delete-share",
          label: "Delete folder share",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Document Workflows",
      items: [
        {
          type: "doc",
          id: "api-reference/get-workflows",
          label: "Get workflows",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-workflow",
          label: "Add workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-workflow",
          label: "Get workflow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/delete-workflow",
          label: "Delete workflow",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/set-workflow",
          label: "Set workflow",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/update-workflow",
          label: "Update workflow",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/get-workflow-documents",
          label: "Get list of documents in workflow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-queues",
          label: "Get queues",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-queue",
          label: "Add queue",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-queue",
          label: "Get queue",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/delete-queue",
          label: "Delete queue",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-workflow-queue-documents",
          label: "Get list of documents in queue",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-document-workflows",
          label: "Get document workflows",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-document-workflow",
          label: "Add document workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-document-workflow",
          label: "Get document workflow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-document-workflow-decisions",
          label: "Approve/Reject document in approval queue",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Antivirus",
      items: [
        {
          type: "doc",
          id: "api-reference/set-antivirus",
          label: "Antivirus document scan",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "User Activities",
      items: [
        {
          type: "doc",
          id: "api-reference/get-user-activities",
          label: "Get user activities",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-document-user-activities",
          label: "Get user activities for a document",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Public",
      items: [
        {
          type: "doc",
          id: "api-reference/public-add-document",
          label: "Public add document",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/public-add-webhook",
          label: "Public add webhook",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Webhooks",
      items: [
        {
          type: "doc",
          id: "api-reference/add-webhook-document",
          label: "Add webhook",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-webhooks",
          label: "Get webhooks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-webhook",
          label: "Add webhook",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-webhook",
          label: "Get webhook",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/delete-webhook",
          label: "Delete webhook",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/update-webhook",
          label: "Update webhook",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/get-webhook-tags",
          label: "Get webhook tags",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-webhook-tag",
          label: "Add webhook tag",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Custom Index",
      items: [
        {
          type: "doc",
          id: "api-reference/index-folder-move",
          label: "IndexFolderMove",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/delete-index",
          label: "DeleteIndex",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/index-search",
          label: "IndexSearch",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Tag Index",
      items: [
        {
          type: "doc",
          id: "api-reference/index-search",
          label: "IndexSearch",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "E-Signature",
      items: [
        {
          type: "doc",
          id: "api-reference/add-docusign-envelopes",
          label: "Create Docusign Envelope request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/add-docusign-recipient-view",
          label: "Create Docusign Recipient View request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/add-esignature-docusign-events",
          label: "Add E-signature event",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "User Management",
      items: [
        {
          type: "doc",
          id: "api-reference/get-groups",
          label: "Get list of user group(s)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-group",
          label: "Add a group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-group",
          label: "Get a user group",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/delete-group",
          label: "Delete Group",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-users-in-group",
          label: "Get users in a group",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-user-to-group",
          label: "Add User to a group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/remove-username-from-group",
          label: "Remove Username From Group",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-users",
          label: "Get list of user(s)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-user",
          label: "Add User",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-user",
          label: "Get a user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/delete-username",
          label: "Delete Username",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-list-of-user-groups",
          label: "Returns a list of group user belongs to",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/set-user-operation",
          label: "Set User Operation",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Case Management",
      items: [
        {
          type: "doc",
          id: "api-reference/get-cases",
          label: "Get Case listing",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-case",
          label: "Add New Case",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-case",
          label: "Get Case details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/update-case",
          label: "Update existing Case",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/delete-case",
          label: "Delete Case",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-case-documents",
          label: "Get list of document in a case",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/delete-case-document",
          label: "Delete Document from Case",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-case-task",
          label: "Get task in a case",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/update-task",
          label: "Update existing Task",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/delete-task",
          label: "Delete Task",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-task-documents",
          label: "Get list of document in a task",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/delete-task-document",
          label: "Delete Document from Task",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-case-nigo",
          label: "Get nigo in a case",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/update-nigo",
          label: "Update existing Nigo",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/delete-nigo",
          label: "Delete Nigo",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-nigo-documents",
          label: "Get list of document in a task",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/delete-nigo-document",
          label: "Delete Document from Nigo",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-case-tasks",
          label: "Get list of tasks in a case",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-task",
          label: "Add New Task",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-case-nigos",
          label: "Get list of Nigos in a case",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-nigo",
          label: "Add New Nigo",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Mappings",
      items: [
        {
          type: "doc",
          id: "api-reference/get-mappings",
          label: "Get Mappings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-mapping",
          label: "Add New Mapping",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-mapping",
          label: "Get Mapping",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/set-mapping",
          label: "Set Mapping",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/delete-mapping",
          label: "Delete Mapping",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Rulesets",
      items: [
        {
          type: "doc",
          id: "api-reference/get-rulesets",
          label: "Get Rulesets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-ruleset",
          label: "Add New Ruleset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-ruleset",
          label: "Get Ruleset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/update-ruleset",
          label: "Update Ruleset",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/delete-ruleset",
          label: "Delete Ruleset",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/get-rules",
          label: "Get Rules",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/add-rule",
          label: "Add New Rule",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/get-rule",
          label: "Get Rule",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/update-rule",
          label: "Update Rule",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/delete-rule",
          label: "Delete Rule",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Examine Objects",
      items: [
        {
          type: "doc",
          id: "api-reference/get-examine-pdf-url",
          label: "Add Examine Pdf",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/get-examine-pdf",
          label: "Add Examine Pdf",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Document Generation",
      items: [
        {
          type: "doc",
          id: "api-reference/add-document-generate",
          label: "Add Document Generate",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Google Integration",
      items: [
        {
          type: "doc",
          id: "api-reference/add-google-document-export",
          label: "Add Google Document Export",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Reindex",
      items: [
        {
          type: "doc",
          id: "api-reference/add-reindex-document",
          label: "Reindex metadata on a document",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
