Console
-------

While FormKiQ Core was built using an API-First design methodology that allows easy integration with existing applications, you can also use the console interface that is set up with FormKiQ Core.

The FormKiQ Console supports:

✅ Adding / Removing Documents

✅ Adding / Removing Document Tags

✅ Search Documents

✅ Executing FormKiQ API Calls within the API Explorer: i.e., you can use API methods directly from within the console

The FormKiQ Console is open source and can be found on https://github.com/formkiq/formkiq-console[Github].

An email will be sent to your AdminEmail address with a link to the FormKiQ Console once the deployment has completed, but you can also find the Console URL in your link:#_outputs[CloudFormation Outputs].

### Users

Each FormKiQ Core deployment creates its own User Pool. By default, FormKiq Core uses the "AdminEmail" parameter to create a user with administrator privileges. FormKiq Core sends a confirmation link to the "AdminEmail" during deployment.

All user maintenance operations can be done via the Amazon Cognito console. To learn how to add additional users see https://docs.aws.amazon.com/cognito/latest/developerguide/managing-users.html[Amazon Cognito's Developer Guide] for instructions.

See link:#_outputs[CloudFormation Outputs] for FormKiQ configuration.

### Groups

During deployment, FormKiQ Core creates three Cognito Groups within its Cognito User Pool:

- Admins
- default
- default_read

Users in the "Admins" group have full access to all documents in FormKiQ Core.

Users in the "default" group will have read/write access to documents in the default siteid.

Users in the "default_read" group will have read-only access to documents in the default siteid.

All group maintenance operations can be done via the Amazon Cognito console. To learn how to add users to a cognito group see https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-user-groups.html[Amazon Cognito's Developer Guide] for instructions.