API Reference
-------------
All endpoints require either Cognito / IAM Authentication unless the URL starts with /public.

Public URLs are disabled by default and can be enabled through the CloudFormation installation.

[.Documents]
=== Documents

[.documentsGet]
==== `GET /documents`

===== Description

**Returns a list of the most recent documents added**, ordered by inserted, descending


// markup not found, no include::{specDir}documents/GET/spec.adoc[opts=optional]



===== Parameters



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| date
| Fetch documents inserted on a certain date (yyyy-MM-dd) 
| -
| null
| 

| tz
| UTC offset to apply to date parameter (IE: -0600) 
| -
| null
| 

| next
| Next page of results token 
| -
| null
| 

| previous
| Previous page of results token 
| -
| null
| 

| siteId
| Site Identifier 
| -
| null
| 

| limit
| Limit Results 
| -
| null
| 

|===


===== Return Type

<<DocumentItemsResults>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<DocumentItemsResults>>

|===

//===== Samples
// markup not found, no include::{snippetDir}documents/GET/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}documents/GET/http-response.adoc[opts=optional]


// file not found, no * wiremock data link :documents/GET/GET.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/GET/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsPost]
==== `POST /documents`


===== Description

**Creates a new document**; body may include document content if less than 5 MB

// markup not found, no include::{specDir}documents/POST/spec.adoc[opts=optional]


===== Parameters


====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| DocumentBody
|  <<DocumentBody>>
| X
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<DocumentPostResponse>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 201
| 201 CREATED
|  <<DocumentPostResponse>>

|===

//===== Samples
// markup not found, no include::{snippetDir}documents/POST/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}documents/POST/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :documents/POST/POST.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/POST/implementation.adoc[opts=optional]


endif::internal-generation[]

[.documentsDocumentIdGet]
==== `GET /documents/{documentId}`

===== Description

**Retrieves a document's details**, i.e., metadata


// markup not found, no include::{specDir}documents/\{documentId\}/GET/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<DocumentItem>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<DocumentItem>>

|===

//===== Samples
// markup not found, no include::{snippetDir}documents/\{documentId\}/GET/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}documents/\{documentId\}/GET/http-response.adoc[opts=optional]


// file not found, no * wiremock data link :documents/{documentId}/GET/GET.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/GET/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdPatch]
==== `PATCH /documents/{documentId}`


===== Description

**Update a document's details**, i.e., metadata


// markup not found, no include::{specDir}documents/\{documentId\}/PATCH/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===

====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| DocumentBody
|  <<DocumentBody>>
| X
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<DocumentPostResponse>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<DocumentPostResponse>>

|===

//===== Samples
// markup not found, no include::{snippetDir}documents/\{documentId\}/PATCH/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}documents/\{documentId\}/PATCH/http-response.adoc[opts=optional]


// file not found, no * wiremock data link :documents/{documentId}/PATCH/PATCH.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/PATCH/implementation.adoc[opts=optional]


endif::internal-generation[]

[.documentsDocumentIdContentGet]
==== `GET /documents/{documentId}/content`



===== Description

**Get a document's contents**


// markup not found, no include::{specDir}documents/\{documentId\}/content/GET/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

| versionId
| Version Identifier 
| -
| null
| 

|===


===== Return Type

<<DocumentContent>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<DocumentContent>>

|===

//===== Samples
// markup not found, no include::{snippetDir}documents/\{documentId\}/content/GET/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}documents/\{documentId\}/content/GET/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :documents/{documentId}/content/GET/GET.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/content/GET/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdDelete]
==== `DELETE /documents/{documentId}`


===== Description

**Delete a document**

// markup not found, no include::{specDir}documents/\{documentId\}/DELETE/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type



-


===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<>>

|===

//===== Samples
// markup not found, no include::{snippetDir}documents/\{documentId\}/DELETE/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}documents/\{documentId\}/DELETE/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :documents/{documentId}/DELETE/DELETE.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/DELETE/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdUploadGet]
==== `GET /documents/{documentId}/upload`


===== Description

**Returns a URL that can be used to upload documents for a specific documentId** (required for documents larger than 5 MB)

// markup not found, no include::{specDir}documents/\{documentId\}/upload/GET/spec.adoc[opts=optional]

===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

| contentLength
| Indicates the size of the entity-body 
| -
| null
| 

| duration
| Indicates the number of hours request is valid for 
| -
| null
| 

|===


===== Return Type

<<DocumentUrl>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<DocumentUrl>>

|===

//===== Samples
// markup not found, no include::{snippetDir}documents/\{documentId\}/upload/GET/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}documents/\{documentId\}/upload/GET/http-response.adoc[opts=optional]


// file not found, no * wiremock data link :documents/{documentId}/upload/GET/GET.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/upload/GET/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdUrlGet]
==== `GET /documents/{documentId}/url`


===== Description

**Returns a URL for the document's contents that expires** (default is 48 hours)


// markup not found, no include::{specDir}documents/\{documentId\}/url/GET/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

| versionId
| Version Identifier 
| -
| null
| 

| duration
| Indicates the number of hours request is valid for 
| X
| null
| 

|===


===== Return Type

<<DocumentUrl>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<DocumentUrl>>

|===

//===== Samples
// markup not found, no include::{snippetDir}documents/\{documentId\}/url/GET/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}documents/\{documentId\}/url/GET/http-response.adoc[opts=optional]


// file not found, no * wiremock data link :documents/{documentId}/url/GET/GET.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/url/GET/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdVersionsGet]
==== `GET /documents/{documentId}/versions`


===== Description

**Get a listing of document content versions**


// markup not found, no include::{specDir}documents/\{documentId\}/versions/GET/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

| next
| Next page of results token 
| -
| null
| 

|===


===== Return Type

<<DocumentItemsVersions>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<DocumentItemsVersions>>

|===

//===== Samples
// markup not found, no include::{snippetDir}documents/\{documentId\}/versions/GET/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}documents/\{documentId\}/versions/GET/http-response.adoc[opts=optional]


// file not found, no * wiremock data link :documents/{documentId}/versions/GET/GET.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/versions/GET/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsUploadGet]
==== `GET /documents/upload`



===== Description

**Returns a URL that can be used to upload document content and create a new document**; required to add content that is larger than 5 MB

// markup not found, no include::{specDir}documents/upload/GET/spec.adoc[opts=optional]



===== Parameters





====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| path
| The upload file&#39;s path 
| -
| null
| 

| siteId
| Site Identifier 
| -
| null
| 

| contentLength
| Indicates the size of the entity-body 
| -
| null
| 

| duration
| Indicates the number of hours request is valid for 
| X
| null
| 

|===


===== Return Type

<<DocumentUrl>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<DocumentUrl>>

|===

//===== Samples
// markup not found, no include::{snippetDir}documents/upload/GET/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}documents/upload/GET/http-response.adoc[opts=optional]


// file not found, no * wiremock data link :documents/upload/GET/GET.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/upload/GET/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsUploadPost]
==== `POST /documents/upload`



===== Description

**Returns a URL that can be used to upload document content and create a new document;** required to add content that is larger than 5 MB


// markup not found, no include::{specDir}documents/upload/POST/spec.adoc[opts=optional]



===== Parameters


====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| DocumentUploadBody
|  <<DocumentUploadBody>>
| X
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

| duration
| Indicates the number of hours request is valid for 
| -
| null
| 

|===


===== Return Type

<<DocumentPostResponse>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 201
| 201 CREATED
|  <<DocumentPostResponse>>

|===

//===== Samples


// markup not found, no include::{snippetDir}documents/upload/POST/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}documents/upload/POST/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :documents/upload/POST/POST.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/upload/POST/implementation.adoc[opts=optional]


endif::internal-generation[]

[.DocumentActions]
=== Document Actions

[.getDocumentActions]
==== `GET /documents/{documentId}/actions`


===== Description

**Document actions request**; Get Document Actions and their Status


// markup not found, no include::{specDir}documents/\{documentId\}/actions/GET/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<DocumentActions>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<DocumentActions>>

|===

===== Samples


// markup not found, no include::{snippetDir}documents/\{documentId\}/actions/GET/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}documents/\{documentId\}/actions/GET/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :documents/{documentId}/actions/GET/GET.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/actions/GET/implementation.adoc[opts=optional]


endif::internal-generation[]

[.DocumentSearch]
=== Document Search

[.searchPost]
==== `POST /search`

===== Description

**Document search query request**; documents are searched primarily using a document tag key and optional tag value, while an optional `documentIds` parameter is also available in the `DocumentSearchBody` to filter within up to 100 documentIds

**NOTE: for fulltext search queries, see link:#post-searchfulltext[`Enterprise API Reference: POST /searchFulltext`]**

// markup not found, no include::{specDir}search/POST/spec.adoc[opts=optional]

===== Parameters

====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| DocumentSearchBody
|  <<DocumentSearchBody>>
| X
| 
| 

|===

====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

| limit
| Limit Results 
| -
| null
| 

| next
| Next page of results token 
| -
| null
| 

| previous
| Previous page of results token 
| -
| null
| 

|===


===== Return Type

<<DocumentSearchResults>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<DocumentSearchResults>>

|===

// ===== Samples
// markup not found, no include::{snippetDir}search/POST/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}search/POST/http-response.adoc[opts=optional]
// file not found, no * wiremock data link :search/POST/POST.json[]

ifdef::internal-generation[]
===== Implementation
// markup not found, no include::{specDir}search/POST/implementation.adoc[opts=optional]
endif::internal-generation[]



[.DocumentTags]
=== Document Tags

[.documentsDocumentIdTagsGet]
==== `GET /documents/{documentId}/tags`

===== Description

**Get a listing of a document's tags**

// markup not found, no include::{specDir}documents/\{documentId\}/tags/GET/spec.adoc[opts=optional]

===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===

====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

| limit
| Limit Results 
| -
| null
| 

| next
| Next page of results token 
| -
| null
| 

| previous
| Previous page of results token 
| -
| null
| 

|===


===== Return Type

<<DocumentItemsTags>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<DocumentItemsTags>>

|===

//===== Samples
// markup not found, no include::{snippetDir}documents/\{documentId\}/tags/GET/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}documents/\{documentId\}/tags/GET/http-response.adoc[opts=optional]

// file not found, no * wiremock data link :documents/{documentId}/tags/GET/GET.json[]

ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/tags/GET/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdTagsPost]
==== `POST /documents/{documentId}/tags`

===== Description

**Add a single tag to a document**; endpoint also accepts a different body parameter for adding multiple tags at one time

// markup not found, no include::{specDir}documents/\{documentId\}/tags/POST/spec.adoc[opts=optional]


===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===

====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| DocumentItemTag
|  <<DocumentItemTag>>
| X
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

-


===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 201
| 201 CREATED
|  <<>>

|===

//===== Samples
// markup not found, no include::{snippetDir}documents/\{documentId\}/tags/POST/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}documents/\{documentId\}/tags/POST/http-response.adoc[opts=optional]

// file not found, no * wiremock data link :documents/{documentId}/tags/POST/POST.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/tags/POST/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdTagsPost_1]
==== `POST /documents/{documentId}/tags`


===== Description

**Add multiple tags to a document**; endpoint also accepts a different body parameter for adding a single tag

// markup not found, no include::{specDir}documents/\{documentId\}/tags#/POST/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===

====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| DocumentTagsPost
|  <<DocumentTagsPost>>
| X
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type



-


===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 201
| 201 CREATED
|  <<>>

|===

//===== Samples
// markup not found, no include::{snippetDir}documents/\{documentId\}/tags#/POST/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}documents/\{documentId\}/tags#/POST/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :documents/{documentId}/tags#/POST/POST.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/tags#/POST/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdTagsTagKeyDelete]
==== `DELETE /documents/{documentId}/tags/{tagKey}`


===== Description

**Delete a document tag by using its key;** if a document has multiple values for this tag key, ALL values for that tag key will be deleted


// markup not found, no include::{specDir}documents/\{documentId\}/tags/\{tagKey\}/DELETE/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

| tagKey
| Tag Key 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type



-


===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<>>

|===

// ===== Samples
// markup not found, no include::{snippetDir}documents/\{documentId\}/tags/\{tagKey\}/DELETE/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}documents/\{documentId\}/tags/\{tagKey\}/DELETE/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :documents/{documentId}/tags/{tagKey}/DELETE/DELETE.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/tags/\{tagKey\}/DELETE/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdTagsTagKeyGet]
==== `GET /documents/{documentId}/tags/{tagKey}`

===== Description

**Get a document tag by using its key**

// markup not found, no include::{specDir}documents/\{documentId\}/tags/\{tagKey\}/GET/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

| tagKey
| Tag Key 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<DocumentItemTag>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<DocumentItemTag>>

|===

//===== Samples
// markup not found, no include::{snippetDir}documents/\{documentId\}/tags/\{tagKey\}/GET/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}documents/\{documentId\}/tags/\{tagKey\}/GET/http-response.adoc[opts=optional]

// file not found, no * wiremock data link :documents/{documentId}/tags/{tagKey}/GET/GET.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/tags/\{tagKey\}/GET/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdTagsTagKeyPut]
==== `PUT /documents/{documentId}/tags/{tagKey}`


===== Description

**Update any and all values of a document tag, by using its key**; you can supply one tag value or a list of tag values in the request body


// markup not found, no include::{specDir}documents/\{documentId\}/tags/\{tagKey\}/PUT/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

| tagKey
| Tag Key 
| X
| null
| 

|===

====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| DocumentItemTagValueBody
|  <<DocumentItemTagValueBody>>
| X
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type



-


===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<>>

|===

// ===== Samples
// markup not found, no include::{snippetDir}documents/\{documentId\}/tags/\{tagKey\}/PUT/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}documents/\{documentId\}/tags/\{tagKey\}/PUT/http-response.adoc[opts=optional]


// file not found, no * wiremock data link :documents/{documentId}/tags/{tagKey}/PUT/PUT.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/tags/\{tagKey\}/PUT/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdTagsTagKeyTagValueDelete]
==== `DELETE /documents/{documentId}/tags/{tagKey}/{tagValue}`


===== Description

**Delete a specific document tag's key/value combination**; the request will be ignored if there is no valid key/value combination found

// markup not found, no include::{specDir}documents/\{documentId\}/tags/\{tagKey\}/\{tagValue\}/DELETE/spec.adoc[opts=optional]


===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

| tagKey
| Tag Key 
| X
| null
| 

| tagValue
| Tag Key Value 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type



-


===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<>>

|===

//===== Samples
// markup not found, no include::{snippetDir}documents/\{documentId\}/tags/\{tagKey\}/\{tagValue\}/DELETE/http-request.adoc[opts=optional]
// markup not found, no include::{snippetDir}documents/\{documentId\}/tags/\{tagKey\}/\{tagValue\}/DELETE/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :documents/{documentId}/tags/{tagKey}/{tagValue}/DELETE/DELETE.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/tags/\{tagKey\}/\{tagValue\}/DELETE/implementation.adoc[opts=optional]


endif::internal-generation[]

[.Miscellaneous]
=== Miscellaneous


[.sitesGet]
//==== sitesGet

`GET /sites`



===== Description

Returns the list of sites that the user has access to


// markup not found, no include::{specDir}sites/GET/spec.adoc[opts=optional]



===== Parameters







===== Return Type

<<Sites>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<Sites>>

|===

//===== Samples


// markup not found, no include::{snippetDir}sites/GET/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}sites/GET/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :sites/GET/GET.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}sites/GET/implementation.adoc[opts=optional]


endif::internal-generation[]


[.versionGet]
//==== versionGet

`GET /version`



===== Description

Return the version of FormKiQ


// markup not found, no include::{specDir}version/GET/spec.adoc[opts=optional]



===== Parameters







===== Return Type

<<Version>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<Version>>

|===

//===== Samples


// markup not found, no include::{snippetDir}version/GET/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}version/GET/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :version/GET/GET.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}version/GET/implementation.adoc[opts=optional]


endif::internal-generation[]


[.Public]
//=== Public


[.publicDocumentsPost]
//==== publicDocumentsPost

`POST /public/documents`



===== Description

Allows unauthenticated creation of new documents; must be enabled during installation (disabled by default)


// markup not found, no include::{specDir}public/documents/POST/spec.adoc[opts=optional]



===== Parameters


====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| DocumentBody
|  <<DocumentBody>>
| X
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<DocumentId>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 201
| 201 CREATED
|  <<DocumentId>>

|===

//===== Samples


// markup not found, no include::{snippetDir}public/documents/POST/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}public/documents/POST/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :public/documents/POST/POST.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}public/documents/POST/implementation.adoc[opts=optional]


endif::internal-generation[]


[.publicWebhooksWebhooksPost]
//==== publicWebhooksWebhooksPost

`POST /public/webhooks/{webhooks+}`



===== Description

Receives an incoming public post to a specified webhook and creates a document based on the data sent; must be enabled during installation (disabled by default)


// markup not found, no include::{specDir}public/webhooks/\{webhooks+\}/POST/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| webhooks+
| Web Hook Param 
| X
| null
| 

|===

====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| body
|  <<object>>
| X
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<DocumentId>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<DocumentId>>

|===

//===== Samples


// markup not found, no include::{snippetDir}public/webhooks/\{webhooks+\}/POST/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}public/webhooks/\{webhooks+\}/POST/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :public/webhooks/{webhooks+}/POST/POST.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}public/webhooks/\{webhooks+\}/POST/implementation.adoc[opts=optional]


endif::internal-generation[]


[.Webhooks]
=== Webhooks


[.privateWebhooksWebhooksPost]
//==== privateWebhooksWebhooksPost

`POST /private/webhooks/{webhooks+}`



===== Description

Receives an incoming private webhook and creates a document based on the webhook's body; requires authentication


// markup not found, no include::{specDir}private/webhooks/\{webhooks+\}/POST/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| webhooks+
| Web Hook Param 
| X
| null
| 

|===

====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| body
|  <<object>>
| X
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<DocumentId>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<DocumentId>>

|===

//===== Samples


// markup not found, no include::{snippetDir}private/webhooks/\{webhooks+\}/POST/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}private/webhooks/\{webhooks+\}/POST/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :private/webhooks/{webhooks+}/POST/POST.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}private/webhooks/\{webhooks+\}/POST/implementation.adoc[opts=optional]


endif::internal-generation[]


[.webhooksGet]
//==== webhooksGet

`GET /webhooks`



===== Description

Returns a list of webhooks; each webhook's id can be provided to an external service, allowing data to be sent, received, and processed via that webhook


// markup not found, no include::{specDir}webhooks/GET/spec.adoc[opts=optional]



===== Parameters





====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<WebhookResults>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<WebhookResults>>

|===

//===== Samples


// markup not found, no include::{snippetDir}webhooks/GET/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}webhooks/GET/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :webhooks/GET/GET.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}webhooks/GET/implementation.adoc[opts=optional]


endif::internal-generation[]


[.webhooksPost]
//==== webhooksPost

`POST /webhooks`



===== Description

Create a new webhook; once created, a webhook's id can be provided to an external service, allowing data to be sent, received, and processed via that webhook


// markup not found, no include::{specDir}webhooks/POST/spec.adoc[opts=optional]



===== Parameters


====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| WebhookBody
|  <<WebhookBody>>
| X
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<WebhookPostResponse>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 201
| 201 CREATED
|  <<WebhookPostResponse>>

|===

//===== Samples


// markup not found, no include::{snippetDir}webhooks/POST/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}webhooks/POST/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :webhooks/POST/POST.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}webhooks/POST/implementation.adoc[opts=optional]


endif::internal-generation[]


[.webhooksWebhookIdDelete]
//==== webhooksWebhookIdDelete

`DELETE /webhooks/{webhookId}`



===== Description

Deletes a webhook; this will disable sending, receiving, or processing of data from external services to this webhook


// markup not found, no include::{specDir}webhooks/\{webhookId\}/DELETE/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| webhookId
| Web Hook Param 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type



-


===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<>>

|===

//===== Samples


// markup not found, no include::{snippetDir}webhooks/\{webhookId\}/DELETE/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}webhooks/\{webhookId\}/DELETE/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :webhooks/{webhookId}/DELETE/DELETE.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}webhooks/\{webhookId\}/DELETE/implementation.adoc[opts=optional]


endif::internal-generation[]


[.webhooksWebhookIdGet]
//==== webhooksWebhookIdGet

`GET /webhooks/{webhookId}`



===== Description

Returns a webhook's details, i.e., its metadata


// markup not found, no include::{specDir}webhooks/\{webhookId\}/GET/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| webhookId
| Web Hook Param 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<Webhook>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<Webhook>>

|===

//===== Samples


// markup not found, no include::{snippetDir}webhooks/\{webhookId\}/GET/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}webhooks/\{webhookId\}/GET/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :webhooks/{webhookId}/GET/GET.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}webhooks/\{webhookId\}/GET/implementation.adoc[opts=optional]


endif::internal-generation[]


[.webhooksWebhookIdPatch]
//==== webhooksWebhookIdPatch

`PATCH /webhooks/{webhookId}`



===== Description

Updates a webhook's details, i.e., its metadata


// markup not found, no include::{specDir}webhooks/\{webhookId\}/PATCH/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| webhookId
| Web Hook Param 
| X
| null
| 

|===

====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| WebhookBody
|  <<WebhookBody>>
| X
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type



-


===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<>>

|===

//===== Samples


// markup not found, no include::{snippetDir}webhooks/\{webhookId\}/PATCH/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}webhooks/\{webhookId\}/PATCH/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :webhooks/{webhookId}/PATCH/PATCH.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}webhooks/\{webhookId\}/PATCH/implementation.adoc[opts=optional]


endif::internal-generation[]


[.webhooksWebhookIdTagsGet]
//==== webhooksWebhookIdTagsGet

`GET /webhooks/{webhookId}/tags`



===== Description

Get a webhook's tags


// markup not found, no include::{specDir}webhooks/\{webhookId\}/tags/GET/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| webhookId
| Web Hook Param 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<WebhookTags>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<WebhookTags>>

|===

//===== Samples


// markup not found, no include::{snippetDir}webhooks/\{webhookId\}/tags/GET/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}webhooks/\{webhookId\}/tags/GET/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :webhooks/{webhookId}/tags/GET/GET.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}webhooks/\{webhookId\}/tags/GET/implementation.adoc[opts=optional]


endif::internal-generation[]


[.webhooksWebhookIdTagsPost]
//==== webhooksWebhookIdTagsPost

`POST /webhooks/{webhookId}/tags`



===== Description

Add a tag to a webhook


// markup not found, no include::{specDir}webhooks/\{webhookId\}/tags/POST/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| webhookId
| Web Hook Param 
| X
| null
| 

|===

====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| DocumentItemTag
|  <<DocumentItemTag>>
| X
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type



-


===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 201
| 200 OK
|  <<>>

|===

//===== Samples


// markup not found, no include::{snippetDir}webhooks/\{webhookId\}/tags/POST/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}webhooks/\{webhookId\}/tags/POST/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :webhooks/{webhookId}/tags/POST/POST.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}webhooks/\{webhookId\}/tags/POST/implementation.adoc[opts=optional]


endif::internal-generation[]


Enterprise API Reference
------------------------

[.fulltextSearchModule]
=== Fulltext Search Module

[.searchFulltextPost]
==== `POST /searchFulltext`


===== Description

**Document fulltext search** (and more robust multi-tag search queries, powered by OpenSearch); ONLY available with FormKiQ Enterprise


// markup not found, no include::{specDir}searchFulltext/POST/spec.adoc[opts=optional]



===== Parameters


====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| DocumentFulltextSearchBody
|  <<DocumentFulltextSearchBody>>
| X
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

| limit
| Limit Results 
| -
| null
| 

|===


===== Return Type

<<FulltextSearchResults>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<FulltextSearchResults>>

|===

===== Samples


// markup not found, no include::{snippetDir}searchFulltext/POST/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}searchFulltext/POST/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :searchFulltext/POST/POST.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}searchFulltext/POST/implementation.adoc[opts=optional]


endif::internal-generation[]

[.documentsDocumentIdFulltextDelete]
==== `DELETE /documents/{documentId}/fulltext`



===== Description

**Removes full text search for a document;** ONLY available with FormKiQ Enterprise


// markup not found, no include::{specDir}documents/\{documentId\}/fulltext/DELETE/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type



-


===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<>>

|===

===== Samples


// markup not found, no include::{snippetDir}documents/\{documentId\}/fulltext/DELETE/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}documents/\{documentId\}/fulltext/DELETE/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :documents/{documentId}/fulltext/DELETE/DELETE.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/fulltext/DELETE/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdFulltextPatch]
==== `PATCH /documents/{documentId}/fulltext`


===== Description

**Updates Opensearch document;** ONLY available with FormKiQ Enterprise


// markup not found, no include::{specDir}documents/\{documentId\}/fulltext/PATCH/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===

====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| FulltextUpdateBody
|  <<FulltextUpdateBody>>
| -
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<FulltextResult>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<FulltextResult>>

|===

===== Samples


// markup not found, no include::{snippetDir}documents/\{documentId\}/fulltext/PATCH/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}documents/\{documentId\}/fulltext/PATCH/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :documents/{documentId}/fulltext/PATCH/PATCH.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/fulltext/PATCH/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdFulltextPut]
==== `PUT /documents/{documentId}/fulltext`



===== Description

**Set all text/tags found within a document to OpenSearch;** ONLY available with FormKiQ Enterprise


// markup not found, no include::{specDir}documents/\{documentId\}/fulltext/PUT/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===

====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| FulltextBody
|  <<FulltextBody>>
| -
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<FulltextResult>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<FulltextResult>>

|===

===== Samples


// markup not found, no include::{snippetDir}documents/\{documentId\}/fulltext/PUT/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}documents/\{documentId\}/fulltext/PUT/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :documents/{documentId}/fulltext/PUT/PUT.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/fulltext/PUT/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdFulltextTagsTagKeyDelete]
==== `DELETE /documents/{documentId}/fulltext/tags/{tagKey}`



===== Description

**Removes document tags from full text search;** ONLY available with FormKiQ Enterprise


// markup not found, no include::{specDir}documents/\{documentId\}/fulltext/tags/\{tagKey\}/DELETE/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

| tagKey
| Tag Key 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type



-


===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<>>

|===

===== Samples


// markup not found, no include::{snippetDir}documents/\{documentId\}/fulltext/tags/\{tagKey\}/DELETE/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}documents/\{documentId\}/fulltext/tags/\{tagKey\}/DELETE/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :documents/{documentId}/fulltext/tags/{tagKey}/DELETE/DELETE.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/fulltext/tags/\{tagKey\}/DELETE/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdFulltextTagsTagKeyTagValueDelete]
==== `DELETE /documents/{documentId}/fulltext/tags/{tagKey}/{tagValue}`


===== Description

**Removes document tag/value from full text search;** ONLY available with FormKiQ Enterprise


// markup not found, no include::{specDir}documents/\{documentId\}/fulltext/tags/\{tagKey\}/\{tagValue\}/DELETE/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

| tagKey
| Tag Key 
| X
| null
| 

| tagValue
| Tag Key Value 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type



-


===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<>>

|===

===== Samples


// markup not found, no include::{snippetDir}documents/\{documentId\}/fulltext/tags/\{tagKey\}/\{tagValue\}/DELETE/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}documents/\{documentId\}/fulltext/tags/\{tagKey\}/\{tagValue\}/DELETE/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :documents/{documentId}/fulltext/tags/{tagKey}/{tagValue}/DELETE/DELETE.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/fulltext/tags/\{tagKey\}/\{tagValue\}/DELETE/implementation.adoc[opts=optional]


endif::internal-generation[]

[.ocrModule]
=== Document Optical Character Recognition (OCR) Module

[.documentsDocumentIdOcrDelete]
==== `DELETE /documents/{documentId}/ocr`



===== Description

**Delete a document optical character recognition (OCR) result, if exists;** ONLY available with FormKiQ Enterprise


// markup not found, no include::{specDir}documents/\{documentId\}/ocr/DELETE/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type



-


===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<>>

|===

===== Samples


// markup not found, no include::{snippetDir}documents/\{documentId\}/ocr/DELETE/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}documents/\{documentId\}/ocr/DELETE/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :documents/{documentId}/ocr/DELETE/DELETE.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/ocr/DELETE/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdOcrGet]
==== `GET /documents/{documentId}/ocr`


===== Description

**Get document optical character recognition (OCR) result, if exists;** ONLY available with FormKiQ Enterprise


// markup not found, no include::{specDir}documents/\{documentId\}/ocr/GET/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<DocumentOcr>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<DocumentOcr>>

|===

===== Samples


// markup not found, no include::{snippetDir}documents/\{documentId\}/ocr/GET/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}documents/\{documentId\}/ocr/GET/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :documents/{documentId}/ocr/GET/GET.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/ocr/GET/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdOcrPost]
==== `POST /documents/{documentId}/ocr`


===== Description

**Document optical character recognition (OCR) request;** extract text and data from a document. ONLY available with FormKiQ Enterprise


// markup not found, no include::{specDir}documents/\{documentId\}/ocr/POST/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===

====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| OcrBody
|  <<OcrBody>>
| -
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<DocumentOcrResult>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<DocumentOcrResult>>

|===

===== Samples


// markup not found, no include::{snippetDir}documents/\{documentId\}/ocr/POST/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}documents/\{documentId\}/ocr/POST/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :documents/{documentId}/ocr/POST/POST.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/ocr/POST/implementation.adoc[opts=optional]


endif::internal-generation[]


[.documentsDocumentIdOcrPut]
==== `PUT /documents/{documentId}/ocr`


===== Description

**Sets a Document optical character recognition (OCR) document.** ONLY available with FormKiQ Enterprise


// markup not found, no include::{specDir}documents/\{documentId\}/ocr/PUT/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| documentId
| Document Identifier 
| X
| null
| 

|===

====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| SetOcrBody
|  <<SetOcrBody>>
| -
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<DocumentOcrResult>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<DocumentOcrResult>>

|===

===== Samples


// markup not found, no include::{snippetDir}documents/\{documentId\}/ocr/PUT/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}documents/\{documentId\}/ocr/PUT/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :documents/{documentId}/ocr/PUT/PUT.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}documents/\{documentId\}/ocr/PUT/implementation.adoc[opts=optional]


endif::internal-generation[]


[.tagSchemasModule]
=== Tag Schemas Module

[.tagSchemasGet]
==== `GET /tagSchemas`



===== Description

**Returns the list of tagSchemas**; ONLY available with FormKiQ Enterprise


// markup not found, no include::{specDir}tagSchemas/GET/spec.adoc[opts=optional]



===== Parameters





====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

| limit
| Limit Results 
| -
| null
| 

| next
| Next page of results token 
| -
| null
| 

| previous
| Previous page of results token 
| -
| null
| 

|===


===== Return Type

<<TagSchemas>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<TagSchemas>>

|===

===== Samples


// markup not found, no include::{snippetDir}tagSchemas/GET/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}tagSchemas/GET/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :tagSchemas/GET/GET.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}tagSchemas/GET/implementation.adoc[opts=optional]


endif::internal-generation[]


[.tagSchemasPost]
==== `POST /tagSchemas`



===== Description

**Creates a new TagSchema**; ONLY available with FormKiQ Enterprise


// markup not found, no include::{specDir}tagSchemas/POST/spec.adoc[opts=optional]



===== Parameters


====== Body Parameter

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| TagSchemaBody
|  <<TagSchemaBody>>
| X
| 
| 

|===



====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<TagSchemaPostResponse>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 201
| 201 CREATED
|  <<TagSchemaPostResponse>>


| 400
| 400 BAD REQUEST
|  <<ErrorsResponse>>

|===



ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}tagSchemas/POST/implementation.adoc[opts=optional]


endif::internal-generation[]

**POST /tagSchemas Examples**

The following POST /tagSchemas body creates two required fields, `playerId` and `caseId`. There is also an optional tag of `category`. 

When the document is saved, a `compositeKey` is created automatically that will allow for a search using both `playerId` and `caseId` as search parameters.

----
{
  "schema": {
    "tags": {
      "compositeKeys": [
        {
          "key": [
            "playerId",
            "caseId"
          ]
        }
      ],
      "required": [
        {
          "key": "playerId"
        },
        {
          "key": "caseId"
        }
      ],
      "optional": [
        {
          "key": "category",
          "allowedValues": [
            "person",
            "city"
          ]
        }
      ],
      "allowAdditionalTags": false,
    }
  }
}
----

**NOTE:** as `allowAdditionalTags` is set to false in this example, any attempt to add additional tags with keys other than `playerId`, `caseId`, or `category` will cause the request to fail. As well, any `category` tag which has a value other than the ones specified, i.e., not `person` or `city`, will also be rejected. By default, this value is true, i.e., additional tags are allowed, if not specified in the schema.

**Specifying Default Values**

Default values can be set for both required and optional tags, and can include one or more values as the default (up to the maximum of five values per tag key, consistent with the multi-value tag specification in FormKiQ Core):

----
{
  "schema": {
    "tags": {
      "required": [
        {
          "key": "planId",
          "default": 1,
        },
        {
          "key": "userId"
        },
        {
          "key": "applicationId"
        }
      ],
      "optional": [
        {
          "key": "components",
          "allowedValues": [
            "idCheck",
            "creditCheck",
            "criticalIllnessInfo"
          ],
          "default": [
            "idCheck",
            "creditCheck"
          ]
        }
      ]
    }
  }
}
----


[.tagSchemasTagSchemaIdDelete]
==== `DELETE /tagSchemas/{tagSchemaId}`



===== Description

**Delete a TagSchema**; ONLY available with FormKiQ Enterprise


// markup not found, no include::{specDir}tagSchemas/\{tagSchemaId\}/DELETE/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| tagSchemaId
| Tag Schema Identifier 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type



-


===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<>>

|===

===== Samples


// markup not found, no include::{snippetDir}tagSchemas/\{tagSchemaId\}/DELETE/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}tagSchemas/\{tagSchemaId\}/DELETE/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :tagSchemas/{tagSchemaId}/DELETE/DELETE.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}tagSchemas/\{tagSchemaId\}/DELETE/implementation.adoc[opts=optional]


endif::internal-generation[]


[.tagSchemasTagSchemaIdGet]
==== `GET /tagSchemas/{tagSchemaId}`



===== Description

**Retrieves a TagSchema's details, i.e., metadata**; ONLY available with FormKiQ Enterprise


// markup not found, no include::{specDir}tagSchemas/\{tagSchemaId\}/GET/spec.adoc[opts=optional]



===== Parameters

====== Path Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| tagSchemaId
| Tag Schema Identifier 
| X
| null
| 

|===




====== Query Parameters

[cols="2,3,1,1,1"]
|===
|Name| Description| Required| Default| Pattern

| siteId
| Site Identifier 
| -
| null
| 

|===


===== Return Type

<<TagSchema>>


===== Content Type

* application/json

===== Responses

.http response codes
[cols="2,3,1"]
|===
| Code | Message | Datatype


| 200
| 200 OK
|  <<TagSchema>>

|===

===== Samples


// markup not found, no include::{snippetDir}tagSchemas/\{tagSchemaId\}/GET/http-request.adoc[opts=optional]


// markup not found, no include::{snippetDir}tagSchemas/\{tagSchemaId\}/GET/http-response.adoc[opts=optional]



// file not found, no * wiremock data link :tagSchemas/{tagSchemaId}/GET/GET.json[]


ifdef::internal-generation[]
===== Implementation

// markup not found, no include::{specDir}tagSchemas/\{tagSchemaId\}/GET/implementation.adoc[opts=optional]


endif::internal-generation[]



[#models]
== Models

[#DeleteFulltextTags]
=== _DeleteFulltextTags_ 



[.fields-DeleteFulltextTags]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| tags
| 
| List  of <<DeleteFulltextTags_tags_inner>>
| List of tags
|  

|===


[#DeleteFulltextTagsTagsInner]
=== _DeleteFulltextTagsTagsInner_ 



[.fields-DeleteFulltextTagsTagsInner]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| key
| 
| String 
| Tag key
|  

| value
| 
| String 
| Tag value
|  

| values
| 
| List  of <<string>>
| Tag values
|  

|===


[#DocumentAction]
=== _DocumentAction_ 



[.fields-DocumentAction]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| status
| 
| String 
| Status of the Document Action (PENDING, COMPLETE, FAILED)
|  

| type
| 
| String 
| Type of Document Action
|  

| userId
| 
| String 
| User who requested the Action
|  

| parameters
| 
| DocumentBodyAction_parameters 
| 
|  

|===


[#DocumentActions]
=== _DocumentActions_ 



[.fields-DocumentActions]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| actions
| 
| List  of <<DocumentAction>>
| List of document actions
|  

|===


[#DocumentBody]
=== _DocumentBody_ 



[.fields-DocumentBody]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| tagSchemaId
| 
| String 
| Tag Schema Id
|  

| path
| 
| String 
| Path or Name of document
|  

| contentType
| 
| String 
| Document Content-Type
|  

| isBase64
| 
| Boolean 
| Is Content Base64 encoded
|  

| content
| X
| String 
| Document content
|  

| tags
| 
| List  of <<WebhookBody_tags_inner>>
| List of tags
|  

| actions
| 
| List  of <<DocumentBodyAction>>
| List of document actions
|  

| documents
| 
| List  of <<DocumentBody_documents_inner>>
| List of related documents
|  

|===


[#DocumentBodyAction]
=== _DocumentBodyAction_ 

Document action

[.fields-DocumentBodyAction]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| type
| 
| String 
| Type of action (supported values: ocr, fulltext)
|  

| parameters
| 
| DocumentBodyAction_parameters 
| 
|  

|===


[#DocumentBodyActionParameters]
=== _DocumentBodyActionParameters_ 



[.fields-DocumentBodyActionParameters]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| ocrParseTypes
| 
| String 
| OCR Parse types - TEXT, FORMS, TABLES
|  

|===


[#DocumentBodyDocumentsInner]
=== _DocumentBodyDocumentsInner_ 



[.fields-DocumentBodyDocumentsInner]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| path
| 
| String 
| Path or Name of document
|  

| contentType
| 
| String 
| Document Content-Type
|  

| isBase64
| 
| Boolean 
| Is Content Base64 encoded
|  

| content
| 
| String 
| Document content
|  

| tags
| 
| List  of <<WebhookBody_tags_inner>>
| List of tags
|  

|===


[#DocumentContent]
=== _DocumentContent_ 



[.fields-DocumentContent]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| content
| 
| String 
| Document content
|  

| contentUrl
| 
| String 
| Url to document content
|  

| contentType
| 
| String 
| Document Content-Type
|  

| isBase64
| 
| Boolean 
| Is Content Base64 encoded
|  

|===


[#DocumentFulltextSearch]
=== _DocumentFulltextSearch_ 

Document full text search criteria

[.fields-DocumentFulltextSearch]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| text
| 
| String 
| Full text search
|  

| tags
| 
| List  of <<DocumentFulltextTag>>
| List of search tags
|  

|===


[#DocumentFulltextSearchBody]
=== _DocumentFulltextSearchBody_ 

Document full text search

[.fields-DocumentFulltextSearchBody]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| query
| X
| DocumentFulltextSearch 
| 
|  

| responseFields
| 
| SearchResponseFields 
| 
|  

|===


[#DocumentFulltextTag]
=== _DocumentFulltextTag_ 



[.fields-DocumentFulltextTag]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| eq
| 
| String 
| Searches for strings that eq
|  

| eqOr
| 
| List  of <<string>>
| Searches for ANY strings that eq
|  

| key
| X
| String 
| Tag key to search
|  

|===


[#DocumentId]
=== _DocumentId_ 



[.fields-DocumentId]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| documentId
| X
| UUID 
| Document Identifier
| uuid 

| siteId
| 
| String 
| Site Identifier
|  

|===


[#DocumentItem]
=== _DocumentItem_ 



[.fields-DocumentItem]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| next
| 
| String 
| Next page of results token
|  

| previous
| 
| String 
| Previous page of results token
|  

| siteId
| 
| String 
| Site Identifier
|  

| path
| X
| String 
| Path or Name of document
|  

| insertedDate
| 
| Date 
| Inserted Timestamp
| date-time 

| checksum
| 
| String 
| Document checksum, changes when document file changes
|  

| documentId
| X
| UUID 
| Document Identifier
| uuid 

| contentType
| 
| String 
| Document Content-Type
|  

| userId
| 
| String 
| User who added document
|  

| contentLength
| 
| Integer 
| Document size
|  

| versionId
| 
| String 
| Document version
|  

| belongsToDocumentId
| 
| String 
| Parent Document Identifier
|  

| documents
| 
| List  of <<DocumentItem_documents_inner>>
| List of related documents
|  

|===


[#DocumentItemDocumentsInner]
=== _DocumentItemDocumentsInner_ 



[.fields-DocumentItemDocumentsInner]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| path
| 
| String 
| Path or Name of document
|  

| insertedDate
| 
| Date 
| Inserted Timestamp
| date-time 

| checksum
| 
| String 
| Document checksum, changes when document file changes
|  

| documentId
| 
| UUID 
| Document Identifier
| uuid 

| contentType
| 
| String 
| Document Content-Type
|  

| userId
| 
| String 
| User who added document
|  

| contentLength
| 
| Integer 
| Document size
|  

| versionId
| 
| String 
| Document version
|  

| belongsToDocumentId
| 
| String 
| Parent Document Identifier
|  

|===


[#DocumentItemResult]
=== _DocumentItemResult_ 



[.fields-DocumentItemResult]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| siteId
| 
| String 
| Site Identifier
|  

| path
| 
| String 
| Path or Name of document
|  

| insertedDate
| 
| Date 
| Inserted Timestamp
| date-time 

| checksum
| 
| String 
| Document checksum, changes when document file changes
|  

| documentId
| 
| UUID 
| Document Identifier
| uuid 

| contentType
| 
| String 
| Document Content-Type
|  

| userId
| 
| String 
| User who added document
|  

| contentLength
| 
| Integer 
| Document size
|  

| versionId
| 
| String 
| Document version
|  

|===


[#DocumentItemTag]
=== _DocumentItemTag_ 



[.fields-DocumentItemTag]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| insertedDate
| 
| String 
| Inserted Timestamp
|  

| documentId
| 
| String 
| Document Identifier
|  

| type
| 
| String 
| Tag type
|  

| userId
| 
| String 
| User who added document
|  

| value
| X
| String 
| Tag value
|  

| values
| 
| List  of <<string>>
| Tag values
|  

| key
| X
| String 
| Tag key
|  

|===


[#DocumentItemTagValueBody]
=== _DocumentItemTagValueBody_ 



[.fields-DocumentItemTagValueBody]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| value
| 
| String 
| Tag value
|  

| values
| 
| List  of <<string>>
| Tag values
|  

|===


[#DocumentItemVersion]
=== _DocumentItemVersion_ 



[.fields-DocumentItemVersion]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| versionId
| X
| String 
| Document version
|  

| lastModifiedDate
| 
| String 
| Last modified date
|  

|===


[#DocumentItemsResults]
=== _DocumentItemsResults_ 



[.fields-DocumentItemsResults]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| next
| 
| String 
| Next page of results token
|  

| previous
| 
| String 
| Previous page of results token
|  

| documents
| 
| List  of <<DocumentItemResult>>
| List of documents
|  

|===


[#DocumentItemsTags]
=== _DocumentItemsTags_ 



[.fields-DocumentItemsTags]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| next
| 
| String 
| Next page of results token
|  

| previous
| 
| String 
| Previous page of results token
|  

| tags
| 
| List  of <<DocumentItemTag>>
| List of tags
|  

|===


[#DocumentItemsVersions]
=== _DocumentItemsVersions_ 



[.fields-DocumentItemsVersions]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| next
| 
| String 
| Next page of results token
|  

| versions
| 
| List  of <<DocumentItemVersion>>
| List of document versions
|  

|===


[#DocumentOcr]
=== _DocumentOcr_ 



[.fields-DocumentOcr]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| data
| 
| String 
| OCR text result
|  

| ocrEngine
| 
| String 
| The OCR technique used
|  

| ocrStatus
| 
| String 
| The status of the OCR request
|  

| contentType
| 
| String 
| Document Content-Type
|  

| isBase64
| 
| Boolean 
| Is Content Base64 encoded
|  

| userId
| 
| String 
| User who requested the OCR
|  

| documentId
| 
| UUID 
| Document Identifier
| uuid 

|===


[#DocumentOcrResult]
=== _DocumentOcrResult_ 



[.fields-DocumentOcrResult]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| message
| 
| String 
| OCR processing message
|  

|===


[#DocumentPostResponse]
=== _DocumentPostResponse_ 



[.fields-DocumentPostResponse]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| documentId
| 
| UUID 
| Document Identifier
| uuid 

| siteId
| 
| String 
| Site Identifier
|  

| uploadUrl
| 
| String 
| Url to upload document to
|  

| documents
| 
| List  of <<DocumentPostResponse_documents_inner>>
| List of related documents
|  

|===


[#DocumentPostResponseDocumentsInner]
=== _DocumentPostResponseDocumentsInner_ 



[.fields-DocumentPostResponseDocumentsInner]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| documentId
| 
| String 
| Document Identifier
|  

| uploadUrl
| 
| String 
| Url to upload document to
|  

|===


[#DocumentSearchBody]
=== _DocumentSearchBody_ 

Document search tag criteria

[.fields-DocumentSearchBody]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| query
| X
| DocumentSearchTag 
| 
|  

| responseFields
| 
| SearchResponseFields 
| 
|  

|===


[#DocumentSearchItemTag]
=== _DocumentSearchItemTag_ 



[.fields-DocumentSearchItemTag]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| beginsWith
| 
| String 
| Searches for strings that begin with
|  

| eq
| 
| String 
| Searches for strings that eq
|  

| eqOr
| 
| List  of <<string>>
| Searches for ANY strings that eq
|  

| key
| X
| String 
| Tag key to search
|  

|===


[#DocumentSearchMatchTag]
=== _DocumentSearchMatchTag_ 



[.fields-DocumentSearchMatchTag]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| key
| 
| String 
| Tag key
|  

| value
| 
| String 
| Tag value
|  

| type
| 
| String 
| Tag type
|  

|===


[#DocumentSearchResults]
=== _DocumentSearchResults_ 



[.fields-DocumentSearchResults]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| next
| 
| String 
| Next page of results token
|  

| previous
| 
| String 
| Previous page of results token
|  

| documents
| 
| List  of <<SearchDocumentItem>>
| List of search result documents
|  

|===


[#DocumentSearchTag]
=== _DocumentSearchTag_ 

Document tag search criteria

[.fields-DocumentSearchTag]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| tag
| X
| DocumentSearchItemTag 
| 
|  

| documentIds
| 
| List  of <<string>>
| List of DocumentIds to filter search results on
|  

|===


[#DocumentTagsPost]
=== _DocumentTagsPost_ 



[.fields-DocumentTagsPost]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| tags
| X
| List  of <<DocumentItemTag>>
| List of tags
|  

|===


[#DocumentUploadBody]
=== _DocumentUploadBody_ 



[.fields-DocumentUploadBody]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| tagSchemaId
| 
| String 
| Tag Schema Id
|  

| path
| 
| String 
| Path or Name of document
|  

| tags
| 
| List  of <<WebhookBody_tags_inner>>
| List of tags
|  

| actions
| 
| List  of <<DocumentBodyAction>>
| List of document actions
|  

|===


[#DocumentUrl]
=== _DocumentUrl_ 



[.fields-DocumentUrl]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| documentId
| 
| String 
| Document Identifier
|  

| url
| 
| String 
| Document content url
|  

|===


[#Error]
=== _Error_ 



[.fields-Error]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| key
| 
| String 
| Error Key
|  

| error
| 
| String 
| Error Message
|  

|===


[#ErrorsResponse]
=== _ErrorsResponse_ 



[.fields-ErrorsResponse]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| errors
| 
| List  of <<Error>>
| List of errors
|  

|===


[#FulltextBody]
=== _FulltextBody_ 



[.fields-FulltextBody]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| contentType
| 
| String 
| Document Content-Type
|  

| content
| 
| String 
| Document content
|  

| contentUrl
| 
| String 
| Url which contains Document content
|  

|===


[#FulltextDocument]
=== _FulltextDocument_ 



[.fields-FulltextDocument]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| siteId
| 
| String 
| Site Identifier
|  

| path
| 
| String 
| Path or Name of document
|  

| insertedDate
| 
| Date 
| Inserted Timestamp
| date-time 

| documentId
| 
| UUID 
| Document Identifier
| uuid 

| createdBy
| 
| String 
| User who added document
|  

| tags
| 
| Object 
| 
|  

|===


[#FulltextResult]
=== _FulltextResult_ 



[.fields-FulltextResult]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| message
| 
| String 
| Full text processing message
|  

|===


[#FulltextSearchResults]
=== _FulltextSearchResults_ 



[.fields-FulltextSearchResults]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| documents
| 
| List  of <<FulltextDocument>>
| List of search result documents
|  

|===


[#FulltextUpdateBody]
=== _FulltextUpdateBody_ 



[.fields-FulltextUpdateBody]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| path
| 
| String 
| Path or Name of document
|  

| content
| 
| String 
| Document content
|  

| tags
| 
| List  of <<DeleteFulltextTags_tags_inner>>
| List of tags
|  

|===


[#OcrBody]
=== _OcrBody_ 



[.fields-OcrBody]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| parseTypes
| 
| List  of <<string>>
| OCR Parse types - TEXT, FORMS, TABLES
|  

|===


[#SearchDocumentItem]
=== _SearchDocumentItem_ 



[.fields-SearchDocumentItem]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| siteId
| 
| String 
| Site Identifier
|  

| path
| 
| String 
| Path or Name of document
|  

| insertedDate
| 
| Date 
| Inserted Timestamp
| date-time 

| checksum
| 
| String 
| Document checksum, changes when document file changes
|  

| documentId
| 
| UUID 
| Document Identifier
| uuid 

| contentType
| 
| String 
| Document Content-Type
|  

| userId
| 
| String 
| User who added document
|  

| contentLength
| 
| Integer 
| Document size
|  

| versionId
| 
| String 
| Document version
|  

| matchedTag
| 
| DocumentSearchMatchTag 
| 
|  

| tags
| 
| Object 
| 
|  

|===


[#SearchResponseFields]
=== _SearchResponseFields_ 



[.fields-SearchResponseFields]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| tags
| 
| List  of <<string>>
| 
|  

|===


[#SetOcrBody]
=== _SetOcrBody_ 



[.fields-SetOcrBody]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| contentType
| 
| String 
| Document Content-Type
|  

| isBase64
| 
| Boolean 
| Is Content Base64 encoded
|  

| content
| X
| String 
| Document content
|  

|===


[#Site]
=== _Site_ 



[.fields-Site]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| siteId
| 
| String 
| Site Identifier
|  

| uploadEmail
| 
| String 
| SiteId document upload email address
|  

|===


[#Sites]
=== _Sites_ 



[.fields-Sites]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| sites
| 
| List  of <<Site>>
| List of sites
|  

|===


[#TagSchema]
=== _TagSchema_ 



[.fields-TagSchema]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| tagSchemaId
| 
| String 
| 
|  

| name
| 
| String 
| 
|  

| userId
| 
| String 
| 
|  

| insertedDate
| 
| Date 
| Inserted Timestamp
| date-time 

| tags
| 
| TagSchemaBody_tags 
| 
|  

|===


[#TagSchemaBody]
=== _TagSchemaBody_ 



[.fields-TagSchemaBody]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| name
| 
| String 
| 
|  

| tags
| 
| TagSchemaBody_tags 
| 
|  

|===


[#TagSchemaBodyTags]
=== _TagSchemaBodyTags_ 



[.fields-TagSchemaBodyTags]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| compositeKeys
| 
| List  of <<TagSchemaCompositeKey>>
| List of Composite Keys
|  

| required
| 
| List  of <<TagSchemaRequired>>
| List of Required Tags
|  

| optional
| 
| List  of <<TagSchemaOptional>>
| List of Optional Tags
|  

| allowAdditionalTags
| 
| Boolean 
| 
|  

|===


[#TagSchemaCompositeKey]
=== _TagSchemaCompositeKey_ 



[.fields-TagSchemaCompositeKey]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| key
| 
| List  of <<string>>
| 
|  

|===


[#TagSchemaOptional]
=== _TagSchemaOptional_ 



[.fields-TagSchemaOptional]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| key
| 
| String 
| 
|  

| defaultValues
| 
| List  of <<string>>
| Default values
|  

| allowedValues
| 
| List  of <<string>>
| Only valid values
|  

|===


[#TagSchemaPostResponse]
=== _TagSchemaPostResponse_ 



[.fields-TagSchemaPostResponse]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| tagSchemaId
| 
| UUID 
| Tag Schema Identifier
| uuid 

|===


[#TagSchemaRequired]
=== _TagSchemaRequired_ 



[.fields-TagSchemaRequired]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| key
| 
| String 
| 
|  

| defaultValues
| 
| List  of <<string>>
| Default values
|  

| allowedValues
| 
| List  of <<string>>
| Only valid values
|  

|===


[#TagSchemaSummary]
=== _TagSchemaSummary_ 



[.fields-TagSchemaSummary]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| tagSchemaId
| 
| String 
| 
|  

| name
| 
| String 
| 
|  

| userId
| 
| String 
| 
|  

| insertedDate
| 
| Date 
| Inserted Timestamp
| date-time 

|===


[#TagSchemas]
=== _TagSchemas_ 



[.fields-TagSchemas]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| schemas
| 
| List  of <<TagSchemaSummary>>
| List of Tag Schemas
|  

| next
| 
| String 
| 
|  

| previous
| 
| String 
| 
|  

|===


[#Version]
=== _Version_ 



[.fields-Version]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| version
| 
| String 
| FormKiQ version
|  

| type
| 
| String 
| FormKiQ type
|  

|===


[#Webhook]
=== _Webhook_ 



[.fields-Webhook]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| siteId
| 
| String 
| Site Identifier
|  

| name
| 
| String 
| Webhook name
|  

| url
| 
| String 
| Webhook url
|  

| insertedDate
| 
| Date 
| Inserted Timestamp
| date-time 

| id
| 
| UUID 
| Webhook Identifier
| uuid 

| userId
| 
| String 
| User who added document
|  

|===


[#WebhookBody]
=== _WebhookBody_ 



[.fields-WebhookBody]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| name
| X
| String 
| Name of webhook
|  

| ttl
| 
| String 
| Webhook time to live (expiry)
|  

| enabled
| 
| String 
| Is webhook enabled
|  

| tags
| 
| List  of <<WebhookBody_tags_inner>>
| List of tags
|  

|===


[#WebhookBodyTagsInner]
=== _WebhookBodyTagsInner_ 



[.fields-WebhookBodyTagsInner]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| key
| 
| String 
| Tag key
|  

| value
| 
| String 
| Tag value
|  

|===


[#WebhookPostResponse]
=== _WebhookPostResponse_ 



[.fields-WebhookPostResponse]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| id
| 
| UUID 
| 
| uuid 

| siteId
| 
| String 
| Site Identifier
|  

|===


[#WebhookResults]
=== _WebhookResults_ 



[.fields-WebhookResults]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| webhooks
| 
| List  of <<Webhook>>
| List of webhooks
|  

|===


[#WebhookTag]
=== _WebhookTag_ 



[.fields-WebhookTag]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| insertedDate
| 
| String 
| Inserted Timestamp
|  

| webhookId
| 
| String 
| Webhook Identifier
|  

| type
| 
| String 
| Tag type
|  

| userId
| 
| String 
| User who added document
|  

| value
| X
| String 
| Tag value
|  

| key
| X
| String 
| Tag key
|  

|===


[#WebhookTags]
=== _WebhookTags_ 



[.fields-WebhookTags]
[cols="2,1,2,4,1"]
|===
| Field Name| Required| Type| Description| Format

| next
| 
| String 
| Next page of results token
|  

| previous
| 
| String 
| Previous page of results token
|  

| tags
| 
| List  of <<WebhookTag>>
| List of webhook tags
|  

|===

