name: build docs.formkiq.com

on:
  push:
    branches:
    - master
jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: Asciidoctoring the docs to pretty HTML!
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: apt-get -y install asciidoctor awscli
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
    - name: Deploy to S3
      run: make deploy

